default:
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: test-dbt-scd2 # You can change it to execute it on your own
      dataset: test_dbt_scd2
      location: US
      timeout_seconds: 300
      priority: interactive
      threads: 10

  target: prod

